FROM python:latest
WORKDIR /app
COPY /_app-inpe/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update -y;
RUN apt-get install -y nano;
RUN apt-get install -y vim;
RUN apt-get install -y net-tools;
RUN apt-get install -y firefox-esr;
RUN apt-get install -y cron
RUN apt-get install -y iputils-ping
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "sleep", "infinity" ]