version: '3'

services:
  php-apache:
    image: php:8.1.16-apache
    build:
      context: .
      dockerfile: dockerfile-php-apache
    container_name: sanjahoje_php-apache
    volumes:
      - ./_web:/var/www/html
      - ./sites-available/:/etc/apache2/sites-available/
    ports:
      - 83:80
    networks:
      rede:
        ipv4_address: 170.14.0.2
    working_dir: /var/www/html
    environment:
      PHP_ERROR_REPORTING: E_ALL & ~E_NOTICE
      PHP_DISPLAY_ERRORS: "Off"
      PHP_DISPLAY_STARTUP_ERRORS: "Off"
      PHP_LOG_ERRORS: "On"
      PHP_MAX_EXECUTION_TIME: 60
      PHP_MEMORY_LIMIT: 128M
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 50M
    depends_on:
          - db

  db:
    image: mariadb:latest
    build:
      context: .
      dockerfile: dockerfile-db
    container_name: sanjahoje_db
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3303:3306
    networks:
      rede:
        ipv4_address: 170.14.0.3
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: db_testes
      MYSQL_USER: aluno
      MYSQL_PASSWORD: my-password
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: sanjahoje_phpmyadmin
    ports:
      - 8083:80
    networks:
      rede:
        ipv4_address: 170.14.0.4
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my-secret-pw
      UPLOAD_LIMIT: 50M
      #PMA_USER: aluno
      #PMA_PASSWORD: my-password
    depends_on:
      - db

  python-inpe:
    build:
      context: .
      dockerfile: dockerfile-python-inpe
    container_name: sanjahoje_python_inpe
    volumes:
      - ./_app-inpe:/app 
    restart: always
    tty: true
    networks:
      rede:
        ipv4_address: 170.14.0.5
    environment:
      TZ: "America/Sao_Paulo"

  python-noticias:
    build:
      context: .
      dockerfile: dockerfile-python-noticias
    container_name: sanjahoje_python_noticias
    volumes:
      - ./_app-noticias:/app 
    restart: always
    tty: true
    networks:
      rede:
        ipv4_address: 170.14.0.6
    environment:
      TZ: "America/Sao_Paulo"

volumes:
  dbdata:

networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 170.14.0.0/24
          gateway: 170.14.0.1